### ISSUE TITLE
Feature request - support for multiple id's.

### ISSUE THREAD

**Issue by MPParsley** [flexperto/behat-testrail-extension#1]
At the moment a Behat scenario can only be associated with one test case id. It might be useful to tag multiple case id's to a single Behat scenario?

**Comment by flexperto** [comment]
Yes, this might be possible. I have to do a small refactoring.

**Comment by MPParsley** [comment]
`extractScenarioTestCaseId` could be renamed to 'extractScenarioTestCaseIds' and return a list.

`scenarioStarted` and `scenarioFinished` could call `extractScenarioTestCaseIds` and loop the results.

**Comment by flexperto** [comment]
@MPParsley thanks for your contribution. I tagged your changes as 1.1.0 in pre-release. Those should be already available on packagist

**Comment by MPParsley** [comment]
Thanks @flexperto!
